name: CICD

on: [push]

jobs:
  ci:
  #  build-test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - run: echo "El repositorio ${{ github.repository }} ha sido clonado con éxito."
        - uses: php-actions/composer@v6
        - run: echo "Instaladas las dependencias de Composer"
        - run: vendor/bin/phpunit tests/
  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          echo "Login exitoso"
      - name: Build
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/ronaldinho:${{ github.sha }} .
          echo "Imagen generada de histórico"
          docker build -t ${{ secrets.DOCKER_USER }}/ronaldinho:latest .
          echo "Imagen generada de última versión"
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/ronaldinho:${{ github.sha }}
          echo "Histórico guardado"
          docker push ${{ secrets.DOCKER_USER }}/ronaldinho:latest
          echo "Última versión subida"

